# Generated by Django 4.0 on 2021-12-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Roster', '0002_armor_elf_unit_orks_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Elf_unit',
            new_name='ElfUnit',
        ),
        migrations.RenameModel(
            old_name='Orks_unit',
            new_name='OrksUnit',
        ),
    ]
