# Generated by Django 4.0 on 2021-12-08 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Roster', '0006_army_alter_elfunit_armor_alter_elfunit_weapons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUnitOrk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Roster.armor')),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Roster.army')),
                ('ork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Roster.orksunit')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Roster.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUnitElf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Roster.armor')),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Roster.army')),
                ('elf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Roster.elfunit')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Roster.weapon')),
            ],
        ),
    ]
