# Generated by Django 4.0 on 2021-12-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roster', '0008_customunitork_amount_customunitork_total_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='point_value',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='elfunit',
            name='point_value',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='orksunit',
            name='point_value',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='point_value',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
