# Generated by Django 4.0 on 2021-12-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roster', '0013_army_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='army',
            name='total_points',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
