# Generated by Django 4.0 on 2021-12-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roster', '0003_rename_elf_unit_elfunit_rename_orks_unit_orksunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orksunit',
            name='weapons',
            field=models.ManyToManyField(null=True, to='Roster.Weapon'),
        ),
    ]
