# Generated by Django 4.0 on 2021-12-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roster', '0009_alter_armor_point_value_alter_elfunit_point_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customunitork',
            name='total_points',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
