# Generated by Django 4.0 on 2021-12-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roster', '0010_alter_customunitork_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customunitork',
            name='total_points',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
