# Generated by Django 4.0 on 2021-12-09 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Roster', '0014_alter_army_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='army',
            name='total_points',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customunitelf',
            name='army',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Roster.army'),
        ),
    ]
