# Generated by Django 4.0 on 2021-12-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Roster', '0017_alter_army_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrksUnit',
            new_name='OrkUnit',
        ),
    ]
